name: flutter_otp_kit
description: A comprehensive Flutter package for OTP (One-Time Password) verification with customizable styling, localization support, and robust functionality.
version: 1.2.1
homepage: https://github.com/seifmoustafa/flutter_otp_kit
repository: https://github.com/seifmoustafa/flutter_otp_kit
issue_tracker: https://github.com/seifmoustafa/flutter_otp_kit/issues
documentation: https://github.com/seifmoustafa/flutter_otp_kit#readme
topics:
  - flutter
  - otp
  - verification
  - ui
  - widgets

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_platform_widgets: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: